### ISSUE TITLE
Bug - Fix refresh routing of app 

### ISSUE THREAD

**Issue by deronsmith** [quanted/hms_angular#25]
Correct the routing in django of the web app so that if the browser is refreshed while on the web app django will route to the web app again, and the web app will go to the page that the app was on previously.  A django route path of /webapp/* should route to webapp and everything caught by * should be passed to the Angular app to load.
Example:
current page = /hms/webapp/output/123456
refresh -> django path pattern matches /hms/webapp/*
redirect to /hms/webapp with output/123456 passed along to Angular which will then load that deep url.

**Comment by brandonmain** [comment]
Angular app now redirects back to home on a page refresh. 
https://github.com/quanted/hms_app/commit/f2ae8f379ce1c7dc87b3ac0eabf9c7e8e842a928

Attempting to preserve page on refresh wasn't working. Theory is that Django is passing the url from the refresh as the new base url to the Angular app so Angular routing is treating it as the new home url. We may fix this issue on the Angular side but for now will use redirecting to home as the intended behavior.
