### ISSUE TITLE
Bug - Execute Simulation fails to execute

### ISSUE THREAD

**Issue by deronsmith** [quanted/hms_angular#46]
Upon clicking execute simulation the loading bar appears but never changes to the sim status window. Looking at the response for compute in the console there is an error message saying that one of the catchments inputs has not been provided. Either the POST to provide the input failed or the GET compute request was received by the API before that catchment's input was saved to the db.

A check of the contents of the GET compute should be done to handle the error case and on success proceed to the sim status page. A successful GET compute will return the status of the simulation, all other cases/errors will return a json dict {"error": error_message}

![image](https://user-images.githubusercontent.com/14054467/135465840-9adce821-563f-4943-b9a0-63bd4cb10dd4.png)

**Comment by jasondunken** [comment]
I have added the functionality of, if the error contains a list of comids, those segments are re-initialized and a request is sent to execute the simulation. This happens until successful  or a maximum of 5 attempts. So far in testing it's only needed to retry one time for each new simulation. If there is an error it is displayed in the console.
